name: YouTube Phonk Uploader

on:
  schedule:
    - cron: '0 */3 * * *'  # Hər 3 saatdan bir avtomatik işləyir
  workflow_dispatch:      # İstədiyin vaxt əllə başlatmaq üçün düyməni saxlayır

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install dropbox google-api-python-client google-auth-oauthlib requests
      - name: Run Script
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python main.py
